package client

type OpenAIMessage struct {
	Role         string        `json:"role"`
	Content      string        `json:"content"`
	ImageURLs    []string      `json:"image_urls"`
	Name         string        `json:"name"`          // Deprecated
	FunctionCall *FunctionCall `json:"function_call"` // Deprecated
	ToolCalls    []ToolCall    `json:"tool_calls"`
	ToolCallID   string        `json:"tool_call_id"`
}

type ToolCall struct {
	ID       string        `json:"id"`
	Type     string        `json:"type"`
	Function *FunctionCall `json:"function"`
}

type FunctionCall struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"` // Encoded in JSON
}

type Function struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Fields      []Field `json:"fields"`
}

type Field struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Required    bool   `json:"required"`
}

type Embedding struct {
	Text      string    `json:"text"`
	Embedding []float32 `json:"embedding"`
}

type Model struct {
	Name          string `json:"name"`
	Type          string `json:"type"` // chat, embedding
	ContextLength int32  `json:"context_length"`
}

// ImageSpec defines the specifications for generating an image
type ImageSpec struct {
	Prompt string `json:"prompt"`
	Style  string `json:"style"` // vivid, natural
}

// Image defines the properties of an image generated by the API
type Image struct {
	URL           string `json:"url"`
	RevisedPrompt string `json:"revised_prompt"`
}

// SpeechSpec defines the specifications for generating speech
type SpeechSpec struct {
	Text  string  `json:"text"`  // max 4096 characters
	Voice string  `json:"voice"` // alloy, echo, fable, onyx, nova, shimmer
	Speed float32 `json:"speed"` // 0.25 -> 4.0, default 1.0
}

// Speech defines the properties of the speech generated by the API
type Speech struct {
	Audio []byte `json:"audio"` // mp3
}

type Subscription struct {
	Name     string `json:"name"`
	Provider string `json:"provider"`
}

// GetRole returns the Role field.
func (m *OpenAIMessage) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

// GetContent returns the Content field.
func (m *OpenAIMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// GetImageURLs returns the ImageURLs field.
func (m *OpenAIMessage) GetImageURLs() []string {
	if m != nil {
		return m.ImageURLs
	}
	return nil
}

// GetName returns the Name field.
func (m *OpenAIMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// GetFunctionCall returns the FunctionCall field.
func (m *OpenAIMessage) GetFunctionCall() *FunctionCall {
	if m != nil {
		return m.FunctionCall
	}
	return nil
}

// GetToolCalls returns the ToolCalls field.
func (m *OpenAIMessage) GetToolCalls() []ToolCall {
	if m != nil {
		return m.ToolCalls
	}
	return nil
}

// GetToolCallID returns the ToolCallID field.
func (m *OpenAIMessage) GetToolCallID() string {
	if m != nil {
		return m.ToolCallID
	}
	return ""
}

// GetID returns the ID field from ToolCall.
func (tc *ToolCall) GetID() string {
	if tc != nil {
		return tc.ID
	}
	return ""
}

// GetType returns the Type field from ToolCall.
func (tc *ToolCall) GetType() string {
	if tc != nil {
		return tc.Type
	}
	return ""
}

// GetFunction returns the Function field from ToolCall.
func (tc *ToolCall) GetFunction() *FunctionCall {
	if tc != nil {
		return tc.Function
	}
	return nil
}

// GetName returns the Name field from FunctionCall.
func (fc *FunctionCall) GetName() string {
	if fc != nil {
		return fc.Name
	}
	return ""
}

// GetArguments returns the Arguments field from FunctionCall.
func (fc *FunctionCall) GetArguments() string {
	if fc != nil {
		return fc.Arguments
	}
	return ""
}

// GetName returns the Name field from Function.
func (f *Function) GetName() string {
	if f != nil {
		return f.Name
	}
	return ""
}

// GetDescription returns the Description field from Function.
func (f *Function) GetDescription() string {
	if f != nil {
		return f.Description
	}
	return ""
}

// GetFields returns the Fields field from Function.
func (f *Function) GetFields() []Field {
	if f != nil {
		return f.Fields
	}
	return nil
}

// GetText returns the Text field from Embedding.
func (e *Embedding) GetText() string {
	if e != nil {
		return e.Text
	}
	return ""
}

// GetEmbedding returns the Embedding field from Embedding.
func (e *Embedding) GetEmbedding() []float32 {
	if e != nil {
		return e.Embedding
	}
	return nil
}

// GetName returns the Name field from Model.
func (m *Model) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// GetType returns the Type field from Model.
func (m *Model) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// GetContextLength returns the ContextLength field from Model.
func (m *Model) GetContextLength() int32 {
	if m != nil {
		return m.ContextLength
	}
	return 0
}

// GetPrompt returns the Prompt field from ImageSpec.
func (is *ImageSpec) GetPrompt() string {
	if is != nil {
		return is.Prompt
	}
	return ""
}

// GetStyle returns the Style field from ImageSpec.
func (is *ImageSpec) GetStyle() string {
	if is != nil {
		return is.Style
	}
	return ""
}

// GetURL returns the URL field from Image.
func (i *Image) GetURL() string {
	if i != nil {
		return i.URL
	}
	return ""
}

// GetRevisedPrompt returns the RevisedPrompt field from Image.
func (i *Image) GetRevisedPrompt() string {
	if i != nil {
		return i.RevisedPrompt
	}
	return ""
}

// GetText returns the Text field from SpeechSpec.
func (ss *SpeechSpec) GetText() string {
	if ss != nil {
		return ss.Text
	}
	return ""
}

// GetVoice returns the Voice field from SpeechSpec.
func (ss *SpeechSpec) GetVoice() string {
	if ss != nil {
		return ss.Voice
	}
	return ""
}

// GetSpeed returns the Speed field from SpeechSpec.
func (ss *SpeechSpec) GetSpeed() float32 {
	if ss != nil {
		return ss.Speed
	}
	return 1.0 // returning default speed
}

// GetAudio returns the Audio field from Speech.
func (s *Speech) GetAudio() []byte {
	if s != nil {
		return s.Audio
	}
	return nil
}

// GetName returns the Name field from Subscription.
func (s *Subscription) GetName() string {
	if s != nil {
		return s.Name
	}
	return ""
}

// GetProvider returns the Provider field from Subscription.
func (s *Subscription) GetProvider() string {
	if s != nil {
		return s.Provider
	}
	return ""
}

// GetName returns the Name field from Field.
func (f *Field) GetName() string {
	if f != nil {
		return f.Name
	}
	return ""
}

// GetDescription returns the Description field from Field.
func (f *Field) GetDescription() string {
	if f != nil {
		return f.Description
	}
	return ""
}

// GetRequired returns the Required field from Field.
func (f *Field) GetRequired() bool {
	if f != nil {
		return f.Required
	}
	return false
}
